------------------ Inicio --------------------
local Utils = {}
------------------ Requires ------------------
local Math = require(script.Parent["Math.Util"])
local Random = require(script.Parent["Random.Util"])
------------------ Variáveis -----------------

------------------ Funções -------------------

Utils.Math = Math
Utils.Random = Random

------------------ Retornos ------------------
return Utils
----------------------------------------------