------------------- Inicio -------------------
local MoonConfigs = {}
------------------- Requires -----------------

------------------ Variáveis -----------------

MoonConfigs.Moon = {
	{Phase = "New Moon", Texture = "rbxassetid://75226596184616", Brightness = -0.02, DurationDays = 7},
	{Phase = "Waxing Crescent", Texture = "rbxassetid://9028103439", Brightness = -0.02, DurationDays = 7},
	{Phase = "First Quarter", Texture = "rbxassetid://9014138816", Brightness = 0, DurationDays = 7},
	{Phase = "Waxing Gibbous", Texture = "rbxassetid://9028249353", Brightness = 0.015, DurationDays = 7},
	{Phase = "Full Moon", Texture = "rbxassetid://9013498676", Brightness = 0.03, DurationDays = 7},
	{Phase = "Waning Gibbous", Texture = "rbxassetid://9028202073", Brightness = 0.015, DurationDays = 7},
	{Phase = "Last Quarter", Texture = "rbxassetid://9014238161", Brightness = 0, DurationDays = 7},
	{Phase = "Waning Crescent", Texture = "rbxassetid://9027816797", Brightness = -0.02, DurationDays = 7}
}

------------------ Retornos ------------------
return MoonConfigs
----------------------------------------------